# Generated by Django 5.2.14 on 2026-06-11 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('server', 'Server'), ('on_device', 'On-device')], max_length=20)),
                ('model_version', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='detection_logs/images/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='detection_logs/thumbnails/')),
                ('detections_json', models.JSONField(blank=True, default=list)),
                ('top_class', models.CharField(blank=True, max_length=120)),
                ('top_confidence', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('app_version', models.CharField(blank=True, max_length=80)),
                ('review_status', models.CharField(choices=[('unknown', 'Unknown'), ('correct', 'Correct'), ('wrong', 'Wrong'), ('ignored', 'Ignored')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_detection_logs', to='datasets.objectclass')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
