# Generated by Django 5.2.14 on 2026-06-11 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidModelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('model_version', models.SlugField(max_length=120, unique=True)),
                ('tflite_file', models.FileField(blank=True, upload_to='android_exports/%Y/%m/')),
                ('labels_file', models.FileField(blank=True, upload_to='android_exports/%Y/%m/')),
                ('metadata_file', models.FileField(blank=True, upload_to='android_exports/%Y/%m/')),
                ('input_size', models.PositiveIntegerField(default=640)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('iou_threshold', models.FloatField(default=0.45)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('export_log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_deployed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='android_model_packages', to=settings.AUTH_USER_MODEL)),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='android_packages', to='models_registry.trainedmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
