# Generated by Django 5.2.14 on 2026-06-11 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_seed_object_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.PositiveIntegerField()),
                ('y_min', models.PositiveIntegerField()),
                ('x_max', models.PositiveIntegerField()),
                ('y_max', models.PositiveIntegerField()),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('review_status', models.CharField(choices=[('unknown', 'Unknown'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs review')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_boxes', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_boxes', to='datasets.uploadedimage')),
                ('object_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_boxes', to='datasets.objectclass')),
            ],
            options={
                'ordering': ['image_id', 'id'],
            },
        ),
    ]
