"""
Django settings for theDetect project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY') or os.environ.get('DJANGO_SECRET_KEY') or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', env_bool('DJANGO_DEBUG', True))

ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,192.168.31.211,detect.thesysm.com,testserver'),
)
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', 'https://detect.thesysm.com')

SERVICE_NAME = 'theDetect'
SERVICE_BASE_URL = os.environ.get('SERVICE_BASE_URL', 'https://detect.thesysm.com')
PROJECT_DATA_DIR = Path(os.environ.get('PROJECT_DATA_DIR') or os.environ.get('PROJECT_DATA_ROOT') or BASE_DIR / 'project_data')
MEDIA_URL = os.environ.get('MEDIA_URL', 'media/')
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', PROJECT_DATA_DIR))
MDETECT_MAX_UPLOAD_SIZE = int(os.environ.get('MDETECT_MAX_UPLOAD_SIZE', 20 * 1024 * 1024))
MDETECT_MAX_IMAGE_LONG_EDGE = int(os.environ.get('MDETECT_MAX_IMAGE_LONG_EDGE', '1280'))
MDETECT_EXPORT_YOLO_BIN = os.environ.get(
    'MDETECT_EXPORT_YOLO_BIN',
    '/home/cskang/miniconda3/envs/mdetect-export/bin/yolo',
)

CHAT_WIDGET_ENABLED = env_bool('CHAT_WIDGET_ENABLED', True)
CHAT_OLLAMA_BASE_URL = os.environ.get('CHAT_OLLAMA_BASE_URL', 'http://127.0.0.1:11434')
CHAT_OLLAMA_MODEL = os.environ.get('CHAT_OLLAMA_MODEL', 'llama3.2-vision:11b')
CHAT_OLLAMA_TIMEOUT_SECONDS = int(os.environ.get('CHAT_OLLAMA_TIMEOUT_SECONDS', '30'))
CHAT_HISTORY_MAX_MESSAGES = int(os.environ.get('CHAT_HISTORY_MAX_MESSAGES', '6'))
CHAT_MESSAGE_MAX_LENGTH = int(os.environ.get('CHAT_MESSAGE_MAX_LENGTH', '1000'))
CHAT_MANUAL_CONTEXT_DOCS = int(os.environ.get('CHAT_MANUAL_CONTEXT_DOCS', '5'))
CHAT_MANUAL_CONTEXT_CHARS = int(os.environ.get('CHAT_MANUAL_CONTEXT_CHARS', '9000'))
CHAT_SYSTEM_PROMPT = os.environ.get(
    'CHAT_SYSTEM_PROMPT',
    '너는 theDetect 서비스의 친절한 AI 안내 챗봇이다. '
    'theDetect는 객체 클래스 관리, 이미지 데이터셋, 라벨링, 데이터셋 빌드, 증강 데이터셋 빌드, YOLO 학습, '
    '모델 레지스트리, Android 모델 export/deployment, Android 앱 MDetect의 Server Mode/On-device Mode, Detection Logs를 다룬다. '
    '반드시 제공된 theDetect manual context를 우선 근거로 답변하고, 근거가 부족하면 추측하지 말고 Manual 확인이 필요하다고 말한다. '
    '답변은 짧고 실무적인 한국어로 한다. 비밀번호, 토큰, 개인정보 입력을 유도하지 않는다.',
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'core',
    'datasets',
    'labeling',
    'training',
    'models_registry',
    'deployment',
    'detection',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'theDetect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.chat_widget',
            ],
        },
    },
]

WSGI_APPLICATION = 'theDetect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get('STATIC_URL', 'static/')
STATIC_ROOT = os.environ.get('STATIC_ROOT')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', False)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', False)
USE_X_FORWARDED_HOST = env_bool('USE_X_FORWARDED_HOST', False)
if os.environ.get('SECURE_PROXY_SSL_HEADER', '1') != '0':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
