# Generated by Django 5.2.14 on 2026-06-14 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mdetect_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='device_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='device_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='last_login_device_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
