# Generated by Django 5.2.14 on 2026-06-11 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('model_path', models.CharField(max_length=500)),
                ('model_format', models.CharField(default='pt', max_length=40)),
                ('class_names_json', models.JSONField(blank=True, default=list)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('is_active_server_model', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trained_model', to='training.trainingjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
