# Generated by Django 5.2.14 on 2026-06-11 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_alter_datasetversion_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('base_model', models.CharField(default='yolo11n.pt', max_length=120)),
                ('imgsz', models.PositiveIntegerField(default=640)),
                ('epochs', models.PositiveIntegerField(default=50)),
                ('batch', models.IntegerField(default=16)),
                ('device', models.CharField(default='auto', max_length=80)),
                ('patience', models.PositiveIntegerField(default=20)),
                ('workers', models.CharField(default='auto', max_length=40)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log_file', models.CharField(blank=True, max_length=500)),
                ('artifacts_path', models.CharField(blank=True, max_length=500)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to=settings.AUTH_USER_MODEL)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_jobs', to='datasets.datasetversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
