# Generated by Django 5.2.14 on 2026-06-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='device',
            field=models.CharField(default='0', max_length=80),
        ),
    ]
